"""One-time verified source import. No network downloads or runtime dependency."""
from pathlib import Path, PurePosixPath
import hashlib
import io
import json
import shutil
import tarfile

root = Path(__file__).resolve().parents[1]
transfer = root / '.github' / 'transfer'
parts = sorted(transfer.glob('part-*.bin'))
if len(parts) != 14:
    raise SystemExit('Expected exactly fourteen source payload parts')
payload = b''.join(p.read_bytes() for p in parts)
expected = '13febf2770e480601d59951580ea4162b7a337bef62c734a7bb30fd9eb7775f6'
if hashlib.sha256(payload).hexdigest() != expected:
    raise SystemExit('Source payload checksum mismatch')
manifest = {}
with tarfile.open(fileobj=io.BytesIO(payload), mode='r:xz') as archive:
    members = archive.getmembers()
    for member in members:
        path = PurePosixPath(member.name)
        if (not member.isfile() or path.is_absolute() or '..' in path.parts
                or not path.parts or path.parts[0] in ('.git', '.github')):
            raise SystemExit(f'Unsafe archive member: {member.name}')
        target = root.joinpath(*path.parts)
        if target.exists():
            raise SystemExit(f'Refusing to overwrite existing file: {member.name}')
    for member in members:
        data = archive.extractfile(member).read()
        target = root.joinpath(*PurePosixPath(member.name).parts)
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_bytes(data)
        manifest[member.name] = hashlib.sha256(data).hexdigest()
(root / 'docs' / 'SOURCE-IMPORT.json').write_text(json.dumps({
    'payloadSHA256': expected,
    'sourceFiles': manifest,
    'notes': 'Original source files verified at import. Distribution, package archives, binary examples and screenshots are regenerated by CI; reports may be refreshed.'
}, indent=2) + '\n')
shutil.rmtree(transfer)
print(f'Verified and extracted {len(manifest)} original source files')
