import test from 'node:test';
import assert from 'node:assert/strict';
import { Graph, History, Raster, packet, retainPacket, releasePacket, stableStringify } from '../dist/packages/core/src/index.js';
import { registry, createPreset, defaults } from '../dist/packages/nodes/src/index.js';
import { TerrainEngine } from '../dist/packages/engine/src/index.js';
import { CpuBackend } from '../dist/packages/kernels/src/index.js';
import { perspective, lookAt, multiply, invert4, transform4 } from '../dist/packages/math/src/index.js';
test('all six starter graphs validate and have a reachable output', () => { for (const key of ['alpine', 'island', 'desert', 'canyon', 'volcano', 'arctic']) {
    const g = new Graph(registry, createPreset(key));
    assert.equal(g.topological(g.project.output).length, 5);
    assert.equal(g.nodes.length, 7);
} });
test('connections reject cycles atomically and replace one input', () => { const g = new Graph(registry), a = g.add('constant'), b = g.add('invert'), c = g.add('levels'); g.connect(a.id, 'height', b.id, 'a'); g.connect(b.id, 'height', c.id, 'a'); const before = g.serialize(); assert.throws(() => g.connect(c.id, 'height', b.id, 'a'), /cycle/); assert.equal(g.serialize(), before); g.connect(a.id, 'height', c.id, 'a'); assert.equal(g.edges.filter(e => e.to === c.id).length, 1); assert.deepEqual(g.topological(c.id), [a.id, c.id]); assert.throws(() => g.connect(a.id, 'flow', b.id, 'a'), /Unknown output/); });
test('project validation rejects malformed parameters, assets, strokes and topology', () => { for (const mutate of [p => p.nodes[0].params.seed = 1.5, p => p.nodes[0].params.height = Infinity, p => p.nodes[0].type = 'not-a-node', p => p.nodes[0].asset = { size: 2, data: [1] }, p => p.nodes[0].strokes = [{ x: 0, y: 0, radius: 0, strength: .1 }], p => p.output = 'missing', p => p.resolution = 4096]) {
    const p = createPreset();
    mutate(p);
    assert.throws(() => new Graph(registry, p));
} assert.throws(() => Graph.parse('null', registry)); assert.throws(() => Graph.parse('[]', registry)); });
test('graph serialization and history snapshots are independent', () => { const g = new Graph(registry, createPreset()), h = new History(2); h.checkpoint(g.project, 'seed'); g.node('base').params.seed = 19; const old = h.undo(g.project); assert.equal(old.nodes[0].params.seed, 42); const next = h.redo(old); assert.equal(next.nodes[0].params.seed, 19); const parsed = Graph.parse(g.serialize(), registry); parsed.nodes[0].params.seed = 8; assert.equal(g.nodes[0].params.seed, 19); for (let i = 0; i < 5; i++)
    h.checkpoint(g.project); assert.equal(h.undoStack.length, 2); });
test('reference counted packet aliases retain exactly one reference per owned field', () => { const r = new Raster(2, { data: new Float32Array(4) }), p = packet(r), q = retainPacket(p); assert.equal(r.refs, 2); releasePacket(p); assert.equal(r.disposed, false); releasePacket(q); assert.equal(r.disposed, true); assert.throws(() => r.retain(), /released/); });
test('stable serialization and matrix inverse are consistent', () => { assert.equal(stableStringify({ b: 2, a: 1 }), stableStringify({ a: 1, b: 2 })); const m = multiply(perspective(.7, 1.5, .02, 50), lookAt([2, 2, 2], [0, 0, 0])), inv = invert4(m), p = [.2, .8, -.3, 1], q = transform4(inv, transform4(m, p)); q.forEach((v, i) => assert.ok(Math.abs(v - p[i]) < 1e-4)); });
test('engine cache ignores layout and invalidates only dependent nodes', async () => { const engine = new TerrainEngine(new CpuBackend()), p = createPreset(); p.resolution = 64; p.nodes.find(n => n.id === 'erode').params.iterations = 4; let b = await engine.build(p); assert.equal(b.metrics.cacheHits, 0); releasePacket(b.result); p.nodes[0].x += 10; b = await engine.build(p); assert.equal(b.metrics.cacheHits, 5); releasePacket(b.result); p.nodes.find(n => n.id === 'surface').params.snowLine = .4; b = await engine.build(p); assert.equal(b.metrics.cacheHits, 3); releasePacket(b.result); p.nodes[0].params.seed++; b = await engine.build(p); assert.equal(b.metrics.cacheHits, 0); releasePacket(b.result); await engine.dispose(); });
test('engine cancellation rejects superseded builds without releasing owned results', async () => { const engine = new TerrainEngine(new CpuBackend()), p = createPreset(); p.resolution = 64; p.nodes.find(n => n.id === 'erode').params.iterations = 4; const first = engine.build(p), firstCheck = assert.rejects(first, { name: 'AbortError' }); const second = engine.build(p); await firstCheck; const { result } = await second; engine.clearCache(); assert.equal(result.height.disposed, false); assert.ok(result.height.data.some(v => v > 0)); releasePacket(result); await engine.dispose(); });
test('cache pruning respects live consumer references', async () => { const e = new TerrainEngine(new CpuBackend(), { cacheBytes: 16384 }), p = createPreset(); p.resolution = 64; p.nodes.find(n => n.id === 'erode').params.iterations = 2; const b = await e.build(p); assert.ok(b.result.height.data.length === 4096); assert.ok(e.cache.size <= 2); e.clearCache(); assert.equal(b.result.height.disposed, false); releasePacket(b.result); await e.dispose(); });
